language : bash
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y ruby ruby-dev rubygems-integration build-essential po-debconf
    - gem install --no-ri --no-rdoc fpm
install: 
    - make
deploy:
    - provider: bintray
      skip_cleanup: true
      file: .bintray.json
      user: camlafit
      key:
          secure: yL6sHJZ7y1I/Wp7mF4JkP13CO7Huyi/vqXXpm1B52yrJ4EgGoj3wAOaAKLrHkqhoOKAFr3IlZrrnhxncsx0TmoYC8mOwd5p8CVW7LPbelWy3X4SONG3/Yg/ohaZn2wpOkG1Hz0771hqBkIoWGLNZryi99XeoOS6BZ2kExbFbyYvkpuM8GVJ2zAtMY54QMsiZGJuDEhrsCbqA9YV5vLnqSuAJsNXnfnXStt2S3G7GFCUL0YE1rpSy1LMER0qLetKivODF8NdK+GGBForg3TY1UY1tDoJ5Xh5oaVUEgaMKjIam782y8MyGjIBDMnANQDdewJW/KEFpNXfO/Rq1eGSoHPQfJD9Ecw8VjzuObMNcwJfLqLs7fFGdyXgOvkxmmreLvL9lcgwbGoVGh2zVtIIAD1BkluBo0rjfIseEhKxOl7/wpZ8p4hV+eg9MwljjvM3KyL+eu9IbHpuFIk8VJhnT23q2GL65iMwApCjW9412RBGy0U5TfTClSDRxPhH8QH0i0tFt23TSrNXAAwi+X+4iFYrTAaE1wCyTWHJukRxEOgXMRkF1K0sSsIMMASOELDxEDCF1cggn444+sf2Pk/W6wxpCwkUOVUMqj+M+cEGp0P6lVtyqh3j4GyJfC3IK6IJSZDhRJIUQHHpKUuXURZ6DHoOBAgDrugeJwmfXpu7ZDIA=
    - provider: bintray
      skip_cleanup: true
      file: .bintray.release.json
      user: camlafit
      key:
          secure: yL6sHJZ7y1I/Wp7mF4JkP13CO7Huyi/vqXXpm1B52yrJ4EgGoj3wAOaAKLrHkqhoOKAFr3IlZrrnhxncsx0TmoYC8mOwd5p8CVW7LPbelWy3X4SONG3/Yg/ohaZn2wpOkG1Hz0771hqBkIoWGLNZryi99XeoOS6BZ2kExbFbyYvkpuM8GVJ2zAtMY54QMsiZGJuDEhrsCbqA9YV5vLnqSuAJsNXnfnXStt2S3G7GFCUL0YE1rpSy1LMER0qLetKivODF8NdK+GGBForg3TY1UY1tDoJ5Xh5oaVUEgaMKjIam782y8MyGjIBDMnANQDdewJW/KEFpNXfO/Rq1eGSoHPQfJD9Ecw8VjzuObMNcwJfLqLs7fFGdyXgOvkxmmreLvL9lcgwbGoVGh2zVtIIAD1BkluBo0rjfIseEhKxOl7/wpZ8p4hV+eg9MwljjvM3KyL+eu9IbHpuFIk8VJhnT23q2GL65iMwApCjW9412RBGy0U5TfTClSDRxPhH8QH0i0tFt23TSrNXAAwi+X+4iFYrTAaE1wCyTWHJukRxEOgXMRkF1K0sSsIMMASOELDxEDCF1cggn444+sf2Pk/W6wxpCwkUOVUMqj+M+cEGp0P6lVtyqh3j4GyJfC3IK6IJSZDhRJIUQHHpKUuXURZ6DHoOBAgDrugeJwmfXpu7ZDIA=
      on:
          tags: true
    - provider: releases
      skip_cleanup: true
      file_glob: true
      file: "./*.deb"
      api_key:
          secure: "kIDGS4LaqEvLgcA2VwUu/dViTPi4k4DWbpKt2+oLNFROFYLScF2v0hh+W1TZRJcgZUQSbQcZfkj6Wcqq1zbSewnlRG2r1JhAs4fq/StBfb14p1kw/BRv8OTYl7I38PEaMqZ0P3UvjSby0n1hIXgpTD6Hq2n8IQXqo9x3FY8WWOjTFXppar21cQG/jdXsOSiNn0xRMlJ6GvR8Qeq9G66c/YYFrrnpDN0IV4LpyrgurV4nMEybFWw5Z/43xBrDdq3RoR+mI+2d4u/+ac2XDTNAIaji5RcdrWkOzgfkWvg8uZbCfjoMdTKSnFVu2oywONgdpETP5eRopHELBqUgx875I3KQ9PKR8c5canA9Tv548HoTY43x+fRa5Zm19k0SQ9h6kL+Es1wxAgrE0NpNoYv4o509DOqRDysUQ8OoRlwwRo8zMj/hpCH1OjEB+UQV6H7u+nmkzU9UNQfPPgjAAw2Lu7kUCwHwyylfxroE2aOtfEP4EnnKkYCQveHzqzTLHjopOZRKNc9glOCnbZh7wVBfiONQCJxiP7i2gSYmVoIB61xaJDXnNwE74a14Wg2DiQt5kqB9RKGa/uGJn1RSzxgxr5ddtbvahe3rp4J0cfvQlESKrcxv21BbfquDqOwCPO6mKDlOCmmR0u4+8EXilZXqPSE8gSFM/xYhv6XbVUKGqBk="
      on:
          tags: true