#!/bin/bash 

case "$1" in
    configure)
        #Add fuse group if required
        groupadd fuse
        #Add alterncpanel to fuse group
        usermod -aG fuse alterncpanel
        #Correct fuse mount /dev/ 
        #https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=617667
        chmod g+rw /dev/fuse
        chgrp fuse /dev/fuse
        #Update configurations variables
        /usr/share/alternc/install/upgrade/alternc-borgbackup.php
    ;;
esac
exit 0